image: node:lts-gallium

services:
  - postgres:latest
  # - name: minio/minio
  #   alias: minio
  #   command: ["server", "/minio"]

variables:
  POSTGRES_PASSWORD: mysecretpassword
  # MINIO_ACCESS_KEY: testadmin
  # MINIO_SECRET_KEY: testpassword

cache:
  paths:
    - node_modules/

test_build:
  script:
    - node --version
    - yarn --version
    - yarn install

    # check formats
    - yarn fmt
    - git diff --exit-code

    # check types
    - yarn tsc

    # prisma
    - export DATABASE_URL="postgres://postgres:mysecretpassword@postgres/postgres"
    - yarn prisma db push
    - yarn prisma db seed

    # build
    - yarn build
