image: node:18

services:
  - postgres:latest
  - name: minio/minio
    alias: minio
    command: ["server", "/minio"]

variables:
  POSTGRES_PASSWORD: mysecretpassword
  MINIO_ACCESS_KEY: testadmin
  MINIO_SECRET_KEY: testpassword

cache:
  paths:
    - .cache
    - node_modules/

test_build:
  script:
    - node --version
    - yarn --version
    - yarn install --cache-folder "$(realpath .)/.cache"

    # check format and type
    - yarn workspace hitwhoj run lint:check
    - yarn workspace hitwhoj run tsc
    - yarn run fmt.check

    # prisma & minio
    - export DATABASE_URL="postgres://postgres:mysecretpassword@postgres/postgres"
    - export S3_END_POINT=minio
    - export S3_ACCESS_KEY=$MINIO_ACCESS_KEY
    - export S3_SECRET_KEY=$MINIO_SECRET_KEY
    - export S3_BUCKET=hitwhoj
    - yarn workspace hitwhoj run prisma db push

    # test
    - yarn workspace hitwhoj run prisma db seed
    - yarn workspace hitwhoj run test

    # build
    - yarn workspace hitwhoj run build
