image: node:lts-gallium

services:
  - postgres:latest
  - name: minio/minio
    alias: minio
    command: ["server", "/minio"]

variables:
  POSTGRES_PASSWORD: mysecretpassword
  MINIO_ACCESS_KEY: testadmin
  MINIO_SECRET_KEY: testpassword

cache:
  paths:
    - .cache/yarn
    - node_modules/

test_build:
  script:
    - node --version
    - yarn --version
    - yarn config set cache-folder "$(realpath .)/.cache/yarn"
    - yarn install

    # check formats
    - yarn prettier --check .

    # prisma
    - export DATABASE_URL="postgres://postgres:mysecretpassword@postgres/postgres"
    - yarn prisma db push
    - yarn prisma db seed

    # minio
    - export S3_ACCESS_KEY=$MINIO_ACCESS_KEY
    - export S3_SECRET_KEY=$MINIO_SECRET_KEY
    - export S3_BUCKET=hitwhoj

    # check types
    - yarn tsc

    # build
    - yarn build
