image: node:lts-gallium

services:
  - postgres:latest
  - name: minio/minio
    alias: minio
    command: ["server", "/minio"]

variables:
  POSTGRES_PASSWORD: mysecretpassword
  MINIO_ACCESS_KEY: testadmin
  MINIO_SECRET_KEY: testpassword

cache:
  paths:
    - .cache/yarn
    - node_modules/

test_build:
  script:
    - node --version
    - yarn --version
    - yarn install --cache-folder "$(realpath .)/.cache/yarn"

    # check format and type
    - yarn fmt:check
    - yarn lint:check
    - yarn tsc

    # prisma & minio
    - export DATABASE_URL="postgres://postgres:mysecretpassword@postgres/postgres"
    - export S3_END_POINT=minio
    - export S3_ACCESS_KEY=$MINIO_ACCESS_KEY
    - export S3_SECRET_KEY=$MINIO_SECRET_KEY
    - export S3_BUCKET=hitwhoj
    - yarn prisma db push

    # test
    - node -r esbuild-register tests/seed.ts
    - yarn test

    # build
    - yarn build
