name: GitHub CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Deploy postgres
        run: |
          docker run -d -p 5432:5432 --name postgres \
                     -e "POSTGRES_PASSWORD=mysecretpassword" \
                     postgres

      - name: Deploy minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=testadmin" \
                     -e "MINIO_SECRET_KEY=testpassword" \
                     minio/minio server /data

      - name: Install dependencies
        run: yarn install

      - name: Check formats
        run: yarn prettier --check .

      - name: Postgres & MinIO
        run: |
          export S3_ACCESS_KEY=$MINIO_ACCESS_KEY
          export S3_SECRET_KEY=$MINIO_SECRET_KEY
          export S3_BUCKET=hitwhoj
          export DATABASE_URL="postgres://postgres:mysecretpassword@localhost:5432/postgres"
          yarn prisma db push
          yarn prisma db seed

      - name: Check types
        run: yarn tsc

      - name: Build
        run: yarn build
